name: publish-curation
on:
  workflow_dispatch:

jobs:
  generate-map:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          MAP_SERVER: "https://mapcore-demo.org/curation/flatmap/make/map"
        run: |
          curl --request POST \
          --header 'authorization: Bearer ${{ secrets.CURATION_SERVER_TOKEN }}' \
          --header 'content-type: application/json' \
          --url $MAP_SERVER \
          --data '{
            "source": "${{ github.server_url }}/${{ github.repository }}",
            "manifest": "manifest.json",
            "commit": "curation"
            }'
